name: deploy-to-production
run-name: 'Deploy to production'

on:
  push:
    branches:
      - main
      - dev

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Ready-Set-Dice/rsd-shared.git
          ref: 'main'
          path: './src/.shared'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - run: npm ci
      - run: npm run build --if-present
  deploy-job:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.GITSERVICE_ED_SSH }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: whoami
      