name: deploy-to-production
run-name: 'Deploy to production'

on:
  push:
    branches:
      - main

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: checkout shared code repo
        uses: actions/checkout@v3
        with:
          repository: Ready-Set-Dice/rsd-shared.git
          ref: 'main'
          path: './src/.shared'
      - name: setup the correct version of node
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - name: npm install, build and test
        run: |
          npm ci
          npm run build --if-present
      - name: archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-and-server
          path: |
            dist
            homepage.js
  deploy-job:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-and-server
          path: ~/download
      - name: Display structure of donlowded files
        run: ls -R
        working-directory: ~/download
      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.DEPLOY_SERVER }}
      #     username: ${{ secrets.DEPLOY_USER }}
      #     key: ${{ secrets.GITSERVICE_ED_SSH }}
      #     port: ${{ secrets.DEPLOY_PORT }}
      #     script_stop: true
      #     script: |
      #       git -C rsd/rsd-shared pull
      #       git -C rsd/rsd-home pull