name: deploy-to-production
run-name: 'Deploy to production'

on:
  push:
    branches:
      - main

jobs:
  build-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - run: npm ci
      - run: npm run build --if-present
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-test-job
    steps:
      - name: SSH My Action
        uses: GPTED/SSH-My-Action@0.1
        with:
          HOST: ${{ secrets.DEPLOY_SERVER }}
          PORT: ${{ secrets.DEPLOY_PORT }}
          USER: ${{ secrets.DEPLOY_USER }}
          PRIVATE_KEY: ${{ secrets.GITSERVICE_ED_SSH }}
          CMD: whoami
      