name: test-dev-code
run-name: 'Test the code pushed to the dev branch'

on:
  push:
    branches:
      - dev

jobs:
  test-goes-here:
    runs-on: ubuntu-latest
    steps:
      - name: Can do tests here
        run: echo placeholder
        