name: test-dev-code
run-name: 'Test the code pushed to the dev branch'

on:
  push:
    branches:
      - dev

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Ready-Set-Dice/rsd-shared.git
          ref: 'main'
          path: './src/.shared'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - run: npm ci
      # We would like to run some tests here maybe
      - run: npm run build --if-present